background_opacity 0
enable_audio_bell no
font_family JetBrains Mono
confirm_os_window_close 0
enabled_layouts Splits
tab_bar_style hidden

# tabs
map ctrl+f>t   new_tab
map ctrl+f>w   select_tab
map ctrl+f>tab next_tab

# panes
map ctrl+f>h launch --location=hsplit
map ctrl+f>v launch --location=vsplit
map ctrl+f>a launch --location=split
map ctrl+f>r layout_action rotate

# focus
map ctrl+f>left neighboring_window left
map ctrl+f>right neighboring_window right
map ctrl+f>up neighboring_window up
map ctrl+f>down neighboring_window down
