background_opacity 0
enable_audio_bell no
font_family JetBrains Mono
confirm_os_window_close 0
enabled_layouts Splits

map ctrl+f>h launch --location=hsplit
map ctrl+f>v launch --location=vsplit
map ctrl+f>a launch --location=split
map ctrl+f>r layout_action rotate

# Move the active window in the indicated direction
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

# Move the active window to the indicated screen edge
map ctrl+shift+up layout_action move_to_screen_edge top
map ctrl+shift+left layout_action move_to_screen_edge left
map ctrl+shift+right layout_action move_to_screen_edge right
map ctrl+shift+down layout_action move_to_screen_edge bottom

# Switch focus to the neighboring window in the indicated direction
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

map ctrl+. layout_action bias 80
